import { LUNA_DESIGNED_SCENARIOS } from '../../apps/edge-api/test/fixtures/luna/designedScenarios'

export function certificationInputHint(message: string, expected: string): string {
  if (!message) return 'Digite a mensagem do roteiro exatamente como exibida, incluindo maiúsculas e pontuação.'
  return message === expected ? 'Mensagem do roteiro conferida. Você pode enviar.' : 'A mensagem difere do roteiro. Confira maiúsculas, espaços e pontuação; nada foi enviado.'
}

// Human-driven UI for the SAME native scenario endpoint, not a preview bot or
// automatic chat runner. It never stores credentials or calls a provider itself.
export function certificationPlayground(sha: string,selection={provider:'groq',model:'openai/gpt-oss-20b'},sample=false) {
  if(!['groq','workers-ai'].includes(selection.provider)||!/^[A-Za-z0-9@/._-]+$/.test(selection.model))throw new Error('LUNA_PROVIDER_NOT_CONFIGURED')
  const nonce=crypto.randomUUID(), data=JSON.stringify({sha,...selection,sample,scenarios:sample?LUNA_DESIGNED_SCENARIOS.filter(s=>[1,6,11,13].includes(s.id)):LUNA_DESIGNED_SCENARIOS}).replaceAll('<','\\u003c')
  return new Response(`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>YuiSync · Luna · Certificação em staging</title>
<style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;background:#0d111a;color:#e7edf6;font:16px system-ui,sans-serif}main{max-width:1100px;margin:32px auto;padding:24px}h1{margin-bottom:8px}small,p{color:#aab7c9}section{background:#161e2c;border:1px solid #334157;border-radius:16px;padding:20px;margin:18px 0}button,a{color:inherit}button{background:#00866b;border:0;border-radius:9px;padding:12px 20px;font:inherit;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}textarea{width:100%;min-height:110px;background:#0d111a;color:inherit;border:1px solid #465572;border-radius:9px;padding:12px;font:inherit}article{padding:14px;border-bottom:1px solid #334157;white-space:pre-wrap;overflow-wrap:anywhere}.user{border-left:4px solid #34d4ad}.assistant{border-left:4px solid #b795ff}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px ui-monospace,monospace}.error{color:#ffa9ac}[hidden]{display:none!important}</style>
<main><small>YuiSync / AI Lab / staging isolado</small><h1>Luna operacional — testes no navegador</h1><p>${selection.provider} · ${selection.model} · somente dados fictícios. WhatsApp e automação de produção desativados.</p><p>SHA: <code id="sha"></code></p><a href="/entrar">Entrar com o administrador exclusivo de staging</a>
<section><label for="block">Bloco de certificação</label> <select id="block"><option value="1">1 — cenários 1–4</option><option value="2">2 — cenários 5–8</option><option value="3">3 — cenários 9–12</option><option value="4">4 — cenários 13–16</option><option value="5">5 — cenários 17–20</option></select><p>Por bloco: até 120 chamadas, 250 mil tokens e 100 mil leituras. Carregar e consultar status não executa o agente.</p><button id="restore">Carregar / retomar certificação</button><p id="status" role="status">Nenhuma chamada ao modelo será feita ao carregar esta tela.</p><pre id="budget"></pre></section>
<section id="scenario" hidden><h2 id="title"></h2><p>Certificação guiada, não chat livre. Próxima mensagem do roteiro (digite abaixo; não há envio automático):</p><pre id="expected"></pre><label for="message">Mensagem para Luna</label><textarea id="message" autocomplete="off" aria-describedby="input-hint"></textarea><p id="input-hint" role="status"></p><p><button id="send" disabled>Enviar para Luna no staging</button></p><div id="chat" aria-live="polite"></div><details><summary>Evidências, ferramentas e validações</summary><pre id="evidence"></pre></details></section></main>
<script nonce="${nonce}">
const config=${data},byId=id=>document.getElementById(id);byId('sha').textContent=config.sha;
let roundId=config.provider+'-ui-'+config.sha.slice(0,12)+(config.sample?'-sample':'-b1'),current=null,busy=false,pending=false,pollTimer=null,pollDelay=2000,lastStatus=null,loaded=false;
if(config.sample){byId('block').hidden=true;byId('status').textContent='Amostra comparativa: cenários 1, 6, 11 e 13. Não equivale à certificação dos 20.'}
async function call(action,body={}){const response=await fetch('/api/ai-lab/luna/certification/'+action,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({roundId,...body})});const payload=await response.json();if(!response.ok)throw Error(payload.code||'Falha no staging');return payload}
function showBudget(value){byId('budget').textContent=JSON.stringify(value,null,2)}
function showMessage(role,text){if(!text)return;const el=document.createElement('article');el.className=role;el.textContent=(role==='user'?'Você: ':'Luna: ')+text;byId('chat').append(el)}
function showExecutionError(receipt){if(receipt.result?.reply)return;const error=receipt.result?.errorCode||receipt.validation?.violations?.[0]||'TURN_WITHOUT_REPLY';const el=document.createElement('article');el.className='error';el.textContent='Diagnóstico de execução (não é uma resposta da Luna): '+error+'. Nenhuma resposta final foi produzida; consulte as evidências. Não reenvie esta operação.';byId('chat').append(el)}
function render(state){
 showBudget({block:state.budget,accumulated:state.aggregate});pending=!!state.job&&['queued','running','waiting_quota'].includes(state.job.status);current=pending?null:state.next;const last=state.receipts.at(-1),visible=current||state.blocked||(pending?state.next:null)||(last?{scenarioId:last.scenario_id,turn:last.turn_id}:null);byId('scenario').hidden=!visible;
 if(visible){
  const s=config.scenarios.find(s=>s.id===visible.scenarioId);byId('title').textContent='Cenário '+s.id+' — '+s.name;
  byId('expected').textContent=current?s.messages[current.turn]:state.complete?'Bloco executado. Revise as respostas e evidências abaixo; não há próximo envio.':'Turno '+(visible.turn+1)+' bloqueado. Não reenvie a mensagem.';
  byId('chat').replaceChildren();byId('evidence').textContent='';
  for(const receipt of state.receipts){const label=document.createElement('p');label.textContent='Cenário '+receipt.scenario_id+' · mensagem '+(receipt.turn_id+1);byId('chat').append(label);for(const m of receipt.messages)showMessage(m.role==='user'?'user':'assistant',m.content);showExecutionError(receipt);byId('evidence').textContent=JSON.stringify(receipt,null,2)}
  if(state.blocked||state.job){const el=document.createElement('article');el.className=pending?'assistant':'error';el.textContent=pending?'Estado: '+state.job.status+'. A execução continua no servidor, mesmo com a aba fechada. Não reenvie.':'Diagnóstico: '+(state.job?.errorCode||state.blocker)+'. Estado e consumo foram preservados; não reenvie.';byId('chat').append(el);byId('evidence').textContent=JSON.stringify({blocked:state.blocked,blocker:state.blocker,job:state.job,lastCompletedStep:state.progress,lastCompletedReceipt:state.receipts.filter(r=>r.scenario_id===s.id).at(-1)||null},null,2)}
 }
 const labels={queued:'Aguardando execução',running:'Executando',waiting_quota:'Aguardando quota',complete:'Concluído',failed:'Falhou',requires_reconciliation:'Requer reconciliação'};
 byId('status').textContent=pending?labels[state.job.status]:current?'Pronto para mensagem '+(current.turn+1)+' de '+config.scenarios.find(s=>s.id===current.scenarioId).messages.length:state.complete?'4 cenários deste bloco executados tecnicamente. Revisão dos transcripts ainda obrigatória.':'Execução bloqueada: '+(state.job?labels[state.job.status]+' — '+(state.job.errorCode||state.blocker):state.blocker||'sem próximo turno');
 const status=state.job?.status??'terminal';pollDelay=status===lastStatus?Math.min(10000,pollDelay+2000):2000;lastStatus=status;enable();schedulePoll()
}
function schedulePoll(){clearTimeout(pollTimer);if(pending&&!document.hidden)pollTimer=setTimeout(refresh,pollDelay)}
async function refresh(){if(busy||document.hidden){schedulePoll();return}busy=true;enable();try{render(await call('browser-state'));loaded=true}catch(e){byId('status').textContent='Consulta falhou: '+e.message+'. Não reenvie o turno.';pollDelay=Math.min(10000,pollDelay+2000);schedulePoll()}finally{busy=false;enable()}}
document.addEventListener('visibilitychange',()=>{clearTimeout(pollTimer);if(!document.hidden&&loaded)refresh()});
byId('block').addEventListener('change',()=>{clearTimeout(pollTimer);roundId=config.provider+'-ui-'+config.sha.slice(0,12)+'-b'+byId('block').value;pending=false;current=null;loaded=false;byId('scenario').hidden=true;byId('status').textContent='Carregue o bloco selecionado; nenhuma chamada foi feita.';enable()});
const inputHint=${certificationInputHint.toString()};
function enable(){const expected=current?config.scenarios.find(s=>s.id===current.scenarioId).messages[current.turn]:null;byId('block').disabled=busy||pending;byId('restore').disabled=busy;byId('send').disabled=busy||!current||byId('message').value!==expected;byId('input-hint').textContent=busy?'Mensagem enviada. Aguarde a execução, sem reenviar.':expected===null?'Execução bloqueada; consulte o diagnóstico.':inputHint(byId('message').value,expected)}
byId('message').addEventListener('input',enable);
byId('restore').addEventListener('click',refresh);
byId('send').addEventListener('click',async()=>{if(busy||!current)return;busy=true;enable();byId('status').textContent='Enviando turno para execução durável…';try{const scenario=config.scenarios.find(s=>s.id===current.scenarioId),turn=current.turn,message=byId('message').value;const result=await call('turn',{sha:config.sha,scenarioId:scenario.id,turn,message,idempotencyKey:roundId+':'+config.sha+':'+scenario.id+':'+turn,limits:{calls:scenario.id===15?36:scenario.id===14?12:6,tokens:100000,rowsRead:20000}});if(!result.accepted||!result.turn_id)throw Error('TURN_ACCEPTANCE_UNCERTAIN');showMessage('user',message);current=null;pending=true;byId('message').value='';render(await call('browser-state'));loaded=true}catch(e){byId('status').textContent=e.message+' — use Carregar / retomar para consultar, não reenvie.';current=null}finally{busy=false;enable()}});
</script></html>`,{headers:{'content-type':'text/html;charset=utf-8','cache-control':'no-store','content-security-policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'`,'x-content-type-options':'nosniff','referrer-policy':'no-referrer'}})
}
