import { LUNA_DESIGNED_SCENARIOS } from '../../apps/edge-api/test/fixtures/luna/designedScenarios'

// Human-driven UI for the SAME native scenario endpoint, not a preview bot or
// automatic chat runner. It never stores credentials or calls a provider itself.
export function certificationPlayground(sha: string) {
  const nonce=crypto.randomUUID(), data=JSON.stringify({sha,scenarios:LUNA_DESIGNED_SCENARIOS}).replaceAll('<','\\u003c')
  return new Response(`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>YuiSync · Luna · Certificação em staging</title>
<style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;background:#0d111a;color:#e7edf6;font:16px system-ui,sans-serif}main{max-width:1100px;margin:32px auto;padding:24px}h1{margin-bottom:8px}small,p{color:#aab7c9}section{background:#161e2c;border:1px solid #334157;border-radius:16px;padding:20px;margin:18px 0}button,a{color:inherit}button{background:#00866b;border:0;border-radius:9px;padding:12px 20px;font:inherit;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}textarea{width:100%;min-height:110px;background:#0d111a;color:inherit;border:1px solid #465572;border-radius:9px;padding:12px;font:inherit}article{padding:14px;border-bottom:1px solid #334157;white-space:pre-wrap;overflow-wrap:anywhere}.user{border-left:4px solid #34d4ad}.assistant{border-left:4px solid #b795ff}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px ui-monospace,monospace}.error{color:#ffa9ac}[hidden]{display:none!important}</style>
<main><small>YuiSync / AI Lab / staging isolado</small><h1>Luna operacional — testes no navegador</h1><p>Groq · openai/gpt-oss-20b · somente dados fictícios. WhatsApp e automação de produção desativados.</p><p>SHA: <code id="sha"></code></p><a href="/entrar">Entrar com o administrador exclusivo de staging</a>
<section><button id="restore">Carregar / retomar certificação</button><p id="status" role="status">Nenhuma chamada ao modelo será feita ao carregar esta tela.</p><pre id="budget"></pre></section>
<section id="scenario" hidden><h2 id="title"></h2><p>Próxima mensagem do roteiro (digite abaixo; não há envio automático):</p><pre id="expected"></pre><label for="message">Mensagem para Luna</label><textarea id="message" autocomplete="off"></textarea><p><button id="send" disabled>Enviar para Luna no staging</button></p><div id="chat" aria-live="polite"></div><details><summary>Evidências, ferramentas e validações</summary><pre id="evidence"></pre></details></section></main>
<script nonce="${nonce}">
const config=${data},roundId='groq-ui-'+config.sha.slice(0,12),byId=id=>document.getElementById(id);byId('sha').textContent=config.sha;
let current=null,busy=false;
async function call(action,body={}){const response=await fetch('/api/ai-lab/luna/certification/'+action,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({roundId,...body})});const payload=await response.json();if(!response.ok)throw Error(payload.code||'Falha no staging');return payload}
function showBudget(value){byId('budget').textContent=JSON.stringify(value,null,2)}
function showMessage(role,text){const el=document.createElement('article');el.className=role;el.textContent=(role==='user'?'Você: ':'Luna: ')+(text||'[Sem resposta conclusiva]');byId('chat').append(el)}
function render(state){showBudget(state.budget);current=state.next;byId('scenario').hidden=!current;if(!current){byId('status').textContent=state.complete?'20 cenários executados tecnicamente. Revisão dos transcripts ainda obrigatória.':'Execução bloqueada: '+(state.blocker||'sem próximo turno');return}const s=config.scenarios.find(s=>s.id===current.scenarioId);byId('title').textContent='Cenário '+s.id+' — '+s.name;byId('expected').textContent=s.messages[current.turn];byId('chat').replaceChildren();for(const receipt of state.receipts.filter(r=>r.scenario_id===s.id)){for(const m of receipt.messages)showMessage(m.role==='user'?'user':'assistant',m.content);byId('evidence').textContent=JSON.stringify(receipt,null,2)}byId('status').textContent='Pronto para mensagem '+(current.turn+1)+' de '+s.messages.length;enable()}
function enable(){byId('send').disabled=busy||!current||byId('message').value!==config.scenarios.find(s=>s.id===current.scenarioId).messages[current.turn]}
byId('message').addEventListener('input',enable);
byId('restore').addEventListener('click',async()=>{busy=true;enable();try{render(await call('browser-state'))}catch(e){byId('status').textContent=e.message}finally{busy=false;enable()}});
byId('send').addEventListener('click',async()=>{if(busy||!current)return;busy=true;enable();byId('status').textContent='Luna processando… não reenvie a mensagem.';try{const scenario=config.scenarios.find(s=>s.id===current.scenarioId),turn=current.turn,message=byId('message').value;const result=await call('turn',{sha:config.sha,scenarioId:scenario.id,turn,message,idempotencyKey:roundId+':'+config.sha+':'+scenario.id+':'+turn,limits:{calls:scenario.id===15?36:scenario.id===14?12:6,tokens:100000,rowsRead:20000}});showMessage('user',message);showMessage('assistant',result.result?.reply);byId('evidence').textContent=JSON.stringify(result,null,2);byId('message').value='';if(!result.validation.passed||!result.metrics){current=null;byId('status').textContent='BLOQUEADO — '+result.validation.violations.join(', ');showBudget(result.budget);return}render(await call('browser-state'))}catch(e){byId('status').textContent=e.message+' — use Carregar / retomar para reconciliar, não reenvie.';current=null}finally{busy=false;enable()}});
</script></html>`,{headers:{'content-type':'text/html;charset=utf-8','cache-control':'no-store','content-security-policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'`,'x-content-type-options':'nosniff','referrer-policy':'no-referrer'}})
}
